[toolchain]
version = "0.24.2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter_program = "G6bKHBqCLmd5fyd78GejYSWQZFsEPffSsU6nLUiXLqFM"

[registry]
url = "https://api.apr.localnet"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
